spring:
  application:
    name: inventory
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=inventory;encrypt=true;trustServerCertificate=true
    username: user
    password: yesh@6289
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none # Use 'none' when using Liquibase to manage schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: "*"
            value:
              default:
                type: com.example.receive.model.Inventory

topic:
  name: inventory-topic

grpc:
  server:
    port: 9090
  client:
    my-service:
        address: static://localhost:9090
        enable-keepalive: true
        negotiation-type: plaintext
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi/openapi.yml
server:
  port: 8081